supergraph:
  listen: 0.0.0.0:4000
  introspection: true

homepage:
  enabled: false

sandbox:
  enabled: true

include_subgraph_errors:
  all: true

persisted_queries:
  enabled: true

# Enable entity caching globally
preview_entity_cache:
  enabled: true
  subgraph:
    all:
      enabled: true



# telemetry:
#   instrumentation:
#     spans:
#       mode: spec_compliant

# headers:
#   all:
#     request:
#       - propagate:
#           matching: .*

