federation_version: =2.8.1
subgraphs:
  products:
    routing_url: http://localhost:4002/
    schema:
      file: ./subgraphs/products/schema.graphql
  users:
    routing_url: http://localhost:4001
    schema:
      file: ./subgraphs/users/schema.graphql
  